# version: '1'
# services:
#   app:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     ports:
#       - "8888:8888"
#     volumes:
#       - ./src:/app/src
#     # command: python /app/src/main.py

services:
  jupyter:
    build:
      context: .
      dockerfile: Dockerfile
    image: my_jupyter_image:latest
    ports:
      - "8888:8888"
    volumes:
      - ./src:/app/src
    command: ["jupyter", "notebook", "--ip=0.0.0.0", "--port=8888", "--allow-root", "--no-browser"]
